name: sundb-ai ##todo: need to deploy a sundb-ai docker image before this can be used

services:
  redis:
    image: redis:6.0.16
    restart: always
    volumes:
      - ./redis-data:/data
    command: ["redis-server", "--loglevel", "warning"]

  backend:
    image: sundbai/backend:0.2.7 ##todo: need to deploy a sundb-ai docker image before this can be used
    restart: always
    depends_on:
      - redis
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - ./data:/shared/data
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "6"

  frontend:
    image: sundbai/frontend:0.2.7 ##todo: need to deploy a sundb-ai docker image before this can be used
    restart: always
    depends_on:
      - backend
    ports:
      - 3000:3000
    environment:
      BASE_URL: http://backend
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "6"

  background:
    image: sundbai/backend:0.2.7 ##todo: need to deploy a sundb-ai docker image before this can be used
    restart: always
    depends_on:
      - redis
    ports:
      - "5555:5555"
    env_file:
      - .env
    volumes:
      - ./data:/shared/data
    command: /usr/bin/supervisord
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "6"

  local-embedding-reranker:
    image: sundbai/local-embedding-reranker:v2 ##todo: need to deploy a sundb-ai docker image before this can be used
    ports:
      - 5001:5001
    # If you are in China, you can uncomment the following environment to speed up the download of models
    # environment:
    #   - HF_ENDPOINT=https://hf-mirror.com
    volumes:
      - ./local-embedding-reranker:/root/.cache/huggingface
    # If you are using NVIDIA GPU, you can uncomment the following lines to enable GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    profiles:
      - local-embedding-reranker
