"""add_image_table

Revision ID: 2248cf6b1ba4
Revises: c7f016a904c1
Create Date: 2025-03-04 19:31:14.744943

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import mysql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2248cf6b1ba4'
down_revision = 'c7f016a904c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'mime_type',
               existing_type=sa.VARCHAR(length=128),
               type_=sqlmodel.sql.sqltypes.AutoString(length=64),
               existing_nullable=False)
    # op.drop_constraint('documents_source_uri_key', 'documents', type_='unique')
    # Conditionally drop the constraint if it exists
    conn = op.get_bind()
    constraint_exists = conn.execute(
        sa.text("""
            SELECT conname 
            FROM pg_constraint 
            WHERE conname = 'documents_source_uri_key'
        """)
    ).fetchone()

    if constraint_exists:
        op.drop_constraint('documents_source_uri_key', 'documents', type_='unique')
    
    # Create images table
    op.create_table('images',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
        sa.Column('caption', sa.Text(), nullable=True),
        sa.Column('text_snippets', sa.Text(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('source_document_id', sa.Integer(), nullable=False),
        sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop images table
    op.drop_table('images')
    
    op.create_unique_constraint('documents_source_uri_key', 'documents', ['source_uri'])
    op.alter_column('documents', 'mime_type',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###

