"""empty message

Revision ID: 8093333c0d87
Revises: 830fd9c44f39
Create Date: 2024-09-24 12:23:48.076576

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8093333c0d87"
down_revision = "830fd9c44f39"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chats", sa.Column("visibility", sa.SmallInteger(), server_default='0', nullable=True))
    op.execute('UPDATE chats SET visibility = 0 WHERE visibility IS NULL')
    op.alter_column('chats', 'visibility', nullable=False, server_default=None)
    # op.execute(
    #     "UPDATE chats SET engine_options = CAST(JSON_UNQUOTE(engine_options) AS JSON);"
    # )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chats", "visibility")
    # ### end Alembic commands ###
